# Site settings
title: Brian MacKie-Mason
# email: bmackiemason@anl.gov
description: > # this means to ignore newlines until "baseurl:"
      I'm a research scientist with the RCS Codes \& Tools Group at Lockheed Martin.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://brianmackiemason.com" # the base hostname & protocol for your site
email: brimacki@gmail.com
twitter_username: 
github_username:  brimacki
linkedin_username:  brimacki

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Postdoctoral Appointee"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
